# Generated by Django 2.1.2 on 2018-11-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmigrayuda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('cuerpo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='fotos/')),
                ('fuente', models.ImageField(max_length=50, upload_to='')),
            ],
        ),
    ]
